# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Watchtower < Formula
  desc "A clean, minimal, terminal-based global intelligence dashboard."
  homepage "https://github.com/lajosdeme/watchtower"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lajosdeme/watchtower/releases/download/v1.0.0/watchtower_Darwin_x86_64.tar.gz"
      sha256 "1f9c1cd9837cd7853566533b4af1d36b8925a1ab13721c6fcad223055f3ec43d"

      define_method(:install) do
        bin.install "watchtower"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lajosdeme/watchtower/releases/download/v1.0.0/watchtower_Darwin_arm64.tar.gz"
      sha256 "0195c6db06a9b745be5da2f0b0545cd88a9504921d0c52f947e118f3a7f93a68"

      define_method(:install) do
        bin.install "watchtower"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lajosdeme/watchtower/releases/download/v1.0.0/watchtower_Linux_x86_64.tar.gz"
      sha256 "f31545438f88871393dd01551284846624d59777a3bb19f0e19c6650be3f39b1"
      define_method(:install) do
        bin.install "watchtower"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lajosdeme/watchtower/releases/download/v1.0.0/watchtower_Linux_arm64.tar.gz"
      sha256 "e44a6374eace701727770adb4c67548148f0da17748834dc3c2b5d9eed8b1da4"
      define_method(:install) do
        bin.install "watchtower"
      end
    end
  end

  test do
    #{bin}/watchtower --version
  end
end
